version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/GiroDelGusto/src:delegated
      - ./src/main/frontend:/GiroDelGusto/src/main/frontend:delegated
    ports:
      - 8080:8080
    networks:
      - pg-network
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: giroDelGusto
    volumes:
      - pg-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - pg-network
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - db
networks:
  pg-network:
volumes:
  pg-data: