version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./src:/GiroDelGusto/src:delegated
#      - ./src/main/frontend:/GiroDelGusto/src/main/frontend:delegated
#    ports:
#      - 8080:8080
#    networks:
#      - pg-network
#    depends_on:
#      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: giroDelGusto
    volumes:
      - pg-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - pg-network
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - db
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  pg-network:
volumes:
  pg-data:

